#! /bin/bash
printf "%s\n" "$(tput bold)$(date) ${BASH_SOURCE[0]}$(tput sgr0)"

# generated by geo_writer.f08.
#  2020-05-10 16:21:59

# counts steps in batch process
export counter=0
export SECONDS=0
function new_step(){
    export counter=$((counter+1))
    export subcounter=0
    echo ""; echo ""
    echo "Step ${counter}: ${1}"
}
function sub_step(){
    subcounter=$((subcounter+1))
    echo ""
    echo "  Substep ${counter}.${subcounter}: ${1}"
}

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n179.4112.txt -179"
echo ""
echo "time used to run PTW-elev-0n179.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n178.4112.txt -178"
echo ""
echo "time used to run PTW-elev-0n178.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n177.4112.txt -177"
echo ""
echo "time used to run PTW-elev-0n177.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n176.4112.txt -176"
echo ""
echo "time used to run PTW-elev-0n176.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n175.4112.txt -175"
echo ""
echo "time used to run PTW-elev-0n175.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n174.4112.txt -174"
echo ""
echo "time used to run PTW-elev-0n174.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n173.4112.txt -173"
echo ""
echo "time used to run PTW-elev-0n173.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n172.4112.txt -172"
echo ""
echo "time used to run PTW-elev-0n172.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n171.4112.txt -171"
echo ""
echo "time used to run PTW-elev-0n171.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n170.4112.txt -170"
echo ""
echo "time used to run PTW-elev-0n170.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n169.4112.txt -169"
echo ""
echo "time used to run PTW-elev-0n169.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n168.4112.txt -168"
echo ""
echo "time used to run PTW-elev-0n168.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n167.4112.txt -167"
echo ""
echo "time used to run PTW-elev-0n167.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n166.4112.txt -166"
echo ""
echo "time used to run PTW-elev-0n166.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n165.4112.txt -165"
echo ""
echo "time used to run PTW-elev-0n165.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n164.4112.txt -164"
echo ""
echo "time used to run PTW-elev-0n164.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n163.4112.txt -163"
echo ""
echo "time used to run PTW-elev-0n163.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n162.4112.txt -162"
echo ""
echo "time used to run PTW-elev-0n162.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n161.4112.txt -161"
echo ""
echo "time used to run PTW-elev-0n161.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n160.4112.txt -160"
echo ""
echo "time used to run PTW-elev-0n160.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n159.4112.txt -159"
echo ""
echo "time used to run PTW-elev-0n159.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n158.4112.txt -158"
echo ""
echo "time used to run PTW-elev-0n158.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n157.4112.txt -157"
echo ""
echo "time used to run PTW-elev-0n157.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n156.4112.txt -156"
echo ""
echo "time used to run PTW-elev-0n156.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n155.4112.txt -155"
echo ""
echo "time used to run PTW-elev-0n155.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n154.4112.txt -154"
echo ""
echo "time used to run PTW-elev-0n154.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n153.4112.txt -153"
echo ""
echo "time used to run PTW-elev-0n153.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n152.4112.txt -152"
echo ""
echo "time used to run PTW-elev-0n152.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n151.4112.txt -151"
echo ""
echo "time used to run PTW-elev-0n151.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n150.4112.txt -150"
echo ""
echo "time used to run PTW-elev-0n150.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n149.4112.txt -149"
echo ""
echo "time used to run PTW-elev-0n149.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n148.4112.txt -148"
echo ""
echo "time used to run PTW-elev-0n148.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n147.4112.txt -147"
echo ""
echo "time used to run PTW-elev-0n147.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n146.4112.txt -146"
echo ""
echo "time used to run PTW-elev-0n146.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n145.4112.txt -145"
echo ""
echo "time used to run PTW-elev-0n145.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n144.4112.txt -144"
echo ""
echo "time used to run PTW-elev-0n144.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n143.4112.txt -143"
echo ""
echo "time used to run PTW-elev-0n143.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n142.4112.txt -142"
echo ""
echo "time used to run PTW-elev-0n142.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n141.4112.txt -141"
echo ""
echo "time used to run PTW-elev-0n141.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n140.4112.txt -140"
echo ""
echo "time used to run PTW-elev-0n140.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n139.4112.txt -139"
echo ""
echo "time used to run PTW-elev-0n139.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n138.4112.txt -138"
echo ""
echo "time used to run PTW-elev-0n138.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n137.4112.txt -137"
echo ""
echo "time used to run PTW-elev-0n137.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n136.4112.txt -136"
echo ""
echo "time used to run PTW-elev-0n136.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n135.4112.txt -135"
echo ""
echo "time used to run PTW-elev-0n135.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n134.4112.txt -134"
echo ""
echo "time used to run PTW-elev-0n134.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n133.4112.txt -133"
echo ""
echo "time used to run PTW-elev-0n133.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n132.4112.txt -132"
echo ""
echo "time used to run PTW-elev-0n132.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n131.4112.txt -131"
echo ""
echo "time used to run PTW-elev-0n131.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n130.4112.txt -130"
echo ""
echo "time used to run PTW-elev-0n130.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n129.4112.txt -129"
echo ""
echo "time used to run PTW-elev-0n129.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n128.4112.txt -128"
echo ""
echo "time used to run PTW-elev-0n128.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n127.4112.txt -127"
echo ""
echo "time used to run PTW-elev-0n127.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n126.4112.txt -126"
echo ""
echo "time used to run PTW-elev-0n126.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n125.4112.txt -125"
echo ""
echo "time used to run PTW-elev-0n125.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n124.4112.txt -124"
echo ""
echo "time used to run PTW-elev-0n124.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n123.4112.txt -123"
echo ""
echo "time used to run PTW-elev-0n123.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n122.4112.txt -122"
echo ""
echo "time used to run PTW-elev-0n122.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n121.4112.txt -121"
echo ""
echo "time used to run PTW-elev-0n121.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n120.4112.txt -120"
echo ""
echo "time used to run PTW-elev-0n120.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n119.4112.txt -119"
echo ""
echo "time used to run PTW-elev-0n119.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n118.4112.txt -118"
echo ""
echo "time used to run PTW-elev-0n118.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n117.4112.txt -117"
echo ""
echo "time used to run PTW-elev-0n117.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n116.4112.txt -116"
echo ""
echo "time used to run PTW-elev-0n116.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n115.4112.txt -115"
echo ""
echo "time used to run PTW-elev-0n115.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n114.4112.txt -114"
echo ""
echo "time used to run PTW-elev-0n114.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n113.4112.txt -113"
echo ""
echo "time used to run PTW-elev-0n113.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n112.4112.txt -112"
echo ""
echo "time used to run PTW-elev-0n112.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n111.4112.txt -111"
echo ""
echo "time used to run PTW-elev-0n111.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n110.4112.txt -110"
echo ""
echo "time used to run PTW-elev-0n110.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n109.4112.txt -109"
echo ""
echo "time used to run PTW-elev-0n109.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n108.4112.txt -108"
echo ""
echo "time used to run PTW-elev-0n108.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n107.4112.txt -107"
echo ""
echo "time used to run PTW-elev-0n107.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n106.4112.txt -106"
echo ""
echo "time used to run PTW-elev-0n106.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n105.4112.txt -105"
echo ""
echo "time used to run PTW-elev-0n105.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n104.4112.txt -104"
echo ""
echo "time used to run PTW-elev-0n104.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n103.4112.txt -103"
echo ""
echo "time used to run PTW-elev-0n103.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n102.4112.txt -102"
echo ""
echo "time used to run PTW-elev-0n102.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n101.4112.txt -101"
echo ""
echo "time used to run PTW-elev-0n101.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n100.4112.txt -100"
echo ""
echo "time used to run PTW-elev-0n100.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n099.4112.txt -99"
echo ""
echo "time used to run PTW-elev-0n099.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n098.4112.txt -98"
echo ""
echo "time used to run PTW-elev-0n098.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n097.4112.txt -97"
echo ""
echo "time used to run PTW-elev-0n097.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n096.4112.txt -96"
echo ""
echo "time used to run PTW-elev-0n096.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n095.4112.txt -95"
echo ""
echo "time used to run PTW-elev-0n095.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n094.4112.txt -94"
echo ""
echo "time used to run PTW-elev-0n094.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n093.4112.txt -93"
echo ""
echo "time used to run PTW-elev-0n093.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n092.4112.txt -92"
echo ""
echo "time used to run PTW-elev-0n092.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n091.4112.txt -91"
echo ""
echo "time used to run PTW-elev-0n091.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n090.4112.txt -90"
echo ""
echo "time used to run PTW-elev-0n090.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n089.4112.txt -89"
echo ""
echo "time used to run PTW-elev-0n089.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n088.4112.txt -88"
echo ""
echo "time used to run PTW-elev-0n088.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n087.4112.txt -87"
echo ""
echo "time used to run PTW-elev-0n087.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n086.4112.txt -86"
echo ""
echo "time used to run PTW-elev-0n086.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n085.4112.txt -85"
echo ""
echo "time used to run PTW-elev-0n085.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n084.4112.txt -84"
echo ""
echo "time used to run PTW-elev-0n084.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n083.4112.txt -83"
echo ""
echo "time used to run PTW-elev-0n083.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n082.4112.txt -82"
echo ""
echo "time used to run PTW-elev-0n082.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n081.4112.txt -81"
echo ""
echo "time used to run PTW-elev-0n081.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n080.4112.txt -80"
echo ""
echo "time used to run PTW-elev-0n080.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n079.4112.txt -79"
echo ""
echo "time used to run PTW-elev-0n079.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n078.4112.txt -78"
echo ""
echo "time used to run PTW-elev-0n078.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n077.4112.txt -77"
echo ""
echo "time used to run PTW-elev-0n077.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n076.4112.txt -76"
echo ""
echo "time used to run PTW-elev-0n076.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n075.4112.txt -75"
echo ""
echo "time used to run PTW-elev-0n075.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n074.4112.txt -74"
echo ""
echo "time used to run PTW-elev-0n074.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n073.4112.txt -73"
echo ""
echo "time used to run PTW-elev-0n073.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n072.4112.txt -72"
echo ""
echo "time used to run PTW-elev-0n072.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n071.4112.txt -71"
echo ""
echo "time used to run PTW-elev-0n071.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n070.4112.txt -70"
echo ""
echo "time used to run PTW-elev-0n070.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n069.4112.txt -69"
echo ""
echo "time used to run PTW-elev-0n069.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n068.4112.txt -68"
echo ""
echo "time used to run PTW-elev-0n068.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n067.4112.txt -67"
echo ""
echo "time used to run PTW-elev-0n067.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n066.4112.txt -66"
echo ""
echo "time used to run PTW-elev-0n066.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n065.4112.txt -65"
echo ""
echo "time used to run PTW-elev-0n065.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n064.4112.txt -64"
echo ""
echo "time used to run PTW-elev-0n064.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n063.4112.txt -63"
echo ""
echo "time used to run PTW-elev-0n063.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n062.4112.txt -62"
echo ""
echo "time used to run PTW-elev-0n062.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n061.4112.txt -61"
echo ""
echo "time used to run PTW-elev-0n061.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n060.4112.txt -60"
echo ""
echo "time used to run PTW-elev-0n060.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n059.4112.txt -59"
echo ""
echo "time used to run PTW-elev-0n059.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n058.4112.txt -58"
echo ""
echo "time used to run PTW-elev-0n058.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n057.4112.txt -57"
echo ""
echo "time used to run PTW-elev-0n057.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n056.4112.txt -56"
echo ""
echo "time used to run PTW-elev-0n056.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n055.4112.txt -55"
echo ""
echo "time used to run PTW-elev-0n055.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n054.4112.txt -54"
echo ""
echo "time used to run PTW-elev-0n054.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n053.4112.txt -53"
echo ""
echo "time used to run PTW-elev-0n053.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n052.4112.txt -52"
echo ""
echo "time used to run PTW-elev-0n052.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n051.4112.txt -51"
echo ""
echo "time used to run PTW-elev-0n051.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n050.4112.txt -50"
echo ""
echo "time used to run PTW-elev-0n050.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n049.4112.txt -49"
echo ""
echo "time used to run PTW-elev-0n049.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n048.4112.txt -48"
echo ""
echo "time used to run PTW-elev-0n048.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n047.4112.txt -47"
echo ""
echo "time used to run PTW-elev-0n047.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n046.4112.txt -46"
echo ""
echo "time used to run PTW-elev-0n046.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n045.4112.txt -45"
echo ""
echo "time used to run PTW-elev-0n045.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n044.4112.txt -44"
echo ""
echo "time used to run PTW-elev-0n044.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n043.4112.txt -43"
echo ""
echo "time used to run PTW-elev-0n043.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n042.4112.txt -42"
echo ""
echo "time used to run PTW-elev-0n042.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n041.4112.txt -41"
echo ""
echo "time used to run PTW-elev-0n041.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n040.4112.txt -40"
echo ""
echo "time used to run PTW-elev-0n040.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n039.4112.txt -39"
echo ""
echo "time used to run PTW-elev-0n039.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n038.4112.txt -38"
echo ""
echo "time used to run PTW-elev-0n038.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n037.4112.txt -37"
echo ""
echo "time used to run PTW-elev-0n037.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n036.4112.txt -36"
echo ""
echo "time used to run PTW-elev-0n036.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n035.4112.txt -35"
echo ""
echo "time used to run PTW-elev-0n035.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n034.4112.txt -34"
echo ""
echo "time used to run PTW-elev-0n034.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n033.4112.txt -33"
echo ""
echo "time used to run PTW-elev-0n033.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n032.4112.txt -32"
echo ""
echo "time used to run PTW-elev-0n032.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n031.4112.txt -31"
echo ""
echo "time used to run PTW-elev-0n031.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n030.4112.txt -30"
echo ""
echo "time used to run PTW-elev-0n030.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n029.4112.txt -29"
echo ""
echo "time used to run PTW-elev-0n029.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n028.4112.txt -28"
echo ""
echo "time used to run PTW-elev-0n028.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n027.4112.txt -27"
echo ""
echo "time used to run PTW-elev-0n027.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n026.4112.txt -26"
echo ""
echo "time used to run PTW-elev-0n026.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n025.4112.txt -25"
echo ""
echo "time used to run PTW-elev-0n025.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n024.4112.txt -24"
echo ""
echo "time used to run PTW-elev-0n024.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n023.4112.txt -23"
echo ""
echo "time used to run PTW-elev-0n023.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n022.4112.txt -22"
echo ""
echo "time used to run PTW-elev-0n022.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n021.4112.txt -21"
echo ""
echo "time used to run PTW-elev-0n021.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n020.4112.txt -20"
echo ""
echo "time used to run PTW-elev-0n020.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n019.4112.txt -19"
echo ""
echo "time used to run PTW-elev-0n019.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n018.4112.txt -18"
echo ""
echo "time used to run PTW-elev-0n018.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n017.4112.txt -17"
echo ""
echo "time used to run PTW-elev-0n017.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n016.4112.txt -16"
echo ""
echo "time used to run PTW-elev-0n016.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n015.4112.txt -15"
echo ""
echo "time used to run PTW-elev-0n015.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n014.4112.txt -14"
echo ""
echo "time used to run PTW-elev-0n014.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n013.4112.txt -13"
echo ""
echo "time used to run PTW-elev-0n013.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n012.4112.txt -12"
echo ""
echo "time used to run PTW-elev-0n012.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n011.4112.txt -11"
echo ""
echo "time used to run PTW-elev-0n011.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n010.4112.txt -10"
echo ""
echo "time used to run PTW-elev-0n010.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n009.4112.txt -9"
echo ""
echo "time used to run PTW-elev-0n009.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n008.4112.txt -8"
echo ""
echo "time used to run PTW-elev-0n008.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n007.4112.txt -7"
echo ""
echo "time used to run PTW-elev-0n007.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n006.4112.txt -6"
echo ""
echo "time used to run PTW-elev-0n006.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n005.4112.txt -5"
echo ""
echo "time used to run PTW-elev-0n005.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n004.4112.txt -4"
echo ""
echo "time used to run PTW-elev-0n004.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n003.4112.txt -3"
echo ""
echo "time used to run PTW-elev-0n003.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n002.4112.txt -2"
echo ""
echo "time used to run PTW-elev-0n002.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0n001.4112.txt -1"
echo ""
echo "time used to run PTW-elev-0n001.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p000.4112.txt 0"
echo ""
echo "time used to run PTW-elev-0p000.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p001.4112.txt 1"
echo ""
echo "time used to run PTW-elev-0p001.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p002.4112.txt 2"
echo ""
echo "time used to run PTW-elev-0p002.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p003.4112.txt 3"
echo ""
echo "time used to run PTW-elev-0p003.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p004.4112.txt 4"
echo ""
echo "time used to run PTW-elev-0p004.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p005.4112.txt 5"
echo ""
echo "time used to run PTW-elev-0p005.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p006.4112.txt 6"
echo ""
echo "time used to run PTW-elev-0p006.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p007.4112.txt 7"
echo ""
echo "time used to run PTW-elev-0p007.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p008.4112.txt 8"
echo ""
echo "time used to run PTW-elev-0p008.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p009.4112.txt 9"
echo ""
echo "time used to run PTW-elev-0p009.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p010.4112.txt 10"
echo ""
echo "time used to run PTW-elev-0p010.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p011.4112.txt 11"
echo ""
echo "time used to run PTW-elev-0p011.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p012.4112.txt 12"
echo ""
echo "time used to run PTW-elev-0p012.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p013.4112.txt 13"
echo ""
echo "time used to run PTW-elev-0p013.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p014.4112.txt 14"
echo ""
echo "time used to run PTW-elev-0p014.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p015.4112.txt 15"
echo ""
echo "time used to run PTW-elev-0p015.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p016.4112.txt 16"
echo ""
echo "time used to run PTW-elev-0p016.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p017.4112.txt 17"
echo ""
echo "time used to run PTW-elev-0p017.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p018.4112.txt 18"
echo ""
echo "time used to run PTW-elev-0p018.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p019.4112.txt 19"
echo ""
echo "time used to run PTW-elev-0p019.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p020.4112.txt 20"
echo ""
echo "time used to run PTW-elev-0p020.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p021.4112.txt 21"
echo ""
echo "time used to run PTW-elev-0p021.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p022.4112.txt 22"
echo ""
echo "time used to run PTW-elev-0p022.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p023.4112.txt 23"
echo ""
echo "time used to run PTW-elev-0p023.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p024.4112.txt 24"
echo ""
echo "time used to run PTW-elev-0p024.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p025.4112.txt 25"
echo ""
echo "time used to run PTW-elev-0p025.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p026.4112.txt 26"
echo ""
echo "time used to run PTW-elev-0p026.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p027.4112.txt 27"
echo ""
echo "time used to run PTW-elev-0p027.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p028.4112.txt 28"
echo ""
echo "time used to run PTW-elev-0p028.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p029.4112.txt 29"
echo ""
echo "time used to run PTW-elev-0p029.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p030.4112.txt 30"
echo ""
echo "time used to run PTW-elev-0p030.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p031.4112.txt 31"
echo ""
echo "time used to run PTW-elev-0p031.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p032.4112.txt 32"
echo ""
echo "time used to run PTW-elev-0p032.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p033.4112.txt 33"
echo ""
echo "time used to run PTW-elev-0p033.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p034.4112.txt 34"
echo ""
echo "time used to run PTW-elev-0p034.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p035.4112.txt 35"
echo ""
echo "time used to run PTW-elev-0p035.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p036.4112.txt 36"
echo ""
echo "time used to run PTW-elev-0p036.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p037.4112.txt 37"
echo ""
echo "time used to run PTW-elev-0p037.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p038.4112.txt 38"
echo ""
echo "time used to run PTW-elev-0p038.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p039.4112.txt 39"
echo ""
echo "time used to run PTW-elev-0p039.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p040.4112.txt 40"
echo ""
echo "time used to run PTW-elev-0p040.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p041.4112.txt 41"
echo ""
echo "time used to run PTW-elev-0p041.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p042.4112.txt 42"
echo ""
echo "time used to run PTW-elev-0p042.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p043.4112.txt 43"
echo ""
echo "time used to run PTW-elev-0p043.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p044.4112.txt 44"
echo ""
echo "time used to run PTW-elev-0p044.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p045.4112.txt 45"
echo ""
echo "time used to run PTW-elev-0p045.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p046.4112.txt 46"
echo ""
echo "time used to run PTW-elev-0p046.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p047.4112.txt 47"
echo ""
echo "time used to run PTW-elev-0p047.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p048.4112.txt 48"
echo ""
echo "time used to run PTW-elev-0p048.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p049.4112.txt 49"
echo ""
echo "time used to run PTW-elev-0p049.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p050.4112.txt 50"
echo ""
echo "time used to run PTW-elev-0p050.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p051.4112.txt 51"
echo ""
echo "time used to run PTW-elev-0p051.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p052.4112.txt 52"
echo ""
echo "time used to run PTW-elev-0p052.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p053.4112.txt 53"
echo ""
echo "time used to run PTW-elev-0p053.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p054.4112.txt 54"
echo ""
echo "time used to run PTW-elev-0p054.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p055.4112.txt 55"
echo ""
echo "time used to run PTW-elev-0p055.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p056.4112.txt 56"
echo ""
echo "time used to run PTW-elev-0p056.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p057.4112.txt 57"
echo ""
echo "time used to run PTW-elev-0p057.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p058.4112.txt 58"
echo ""
echo "time used to run PTW-elev-0p058.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p059.4112.txt 59"
echo ""
echo "time used to run PTW-elev-0p059.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p060.4112.txt 60"
echo ""
echo "time used to run PTW-elev-0p060.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p061.4112.txt 61"
echo ""
echo "time used to run PTW-elev-0p061.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p062.4112.txt 62"
echo ""
echo "time used to run PTW-elev-0p062.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p063.4112.txt 63"
echo ""
echo "time used to run PTW-elev-0p063.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p064.4112.txt 64"
echo ""
echo "time used to run PTW-elev-0p064.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p065.4112.txt 65"
echo ""
echo "time used to run PTW-elev-0p065.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p066.4112.txt 66"
echo ""
echo "time used to run PTW-elev-0p066.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p067.4112.txt 67"
echo ""
echo "time used to run PTW-elev-0p067.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p068.4112.txt 68"
echo ""
echo "time used to run PTW-elev-0p068.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p069.4112.txt 69"
echo ""
echo "time used to run PTW-elev-0p069.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p070.4112.txt 70"
echo ""
echo "time used to run PTW-elev-0p070.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p071.4112.txt 71"
echo ""
echo "time used to run PTW-elev-0p071.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p072.4112.txt 72"
echo ""
echo "time used to run PTW-elev-0p072.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p073.4112.txt 73"
echo ""
echo "time used to run PTW-elev-0p073.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p074.4112.txt 74"
echo ""
echo "time used to run PTW-elev-0p074.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p075.4112.txt 75"
echo ""
echo "time used to run PTW-elev-0p075.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p076.4112.txt 76"
echo ""
echo "time used to run PTW-elev-0p076.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p077.4112.txt 77"
echo ""
echo "time used to run PTW-elev-0p077.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p078.4112.txt 78"
echo ""
echo "time used to run PTW-elev-0p078.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p079.4112.txt 79"
echo ""
echo "time used to run PTW-elev-0p079.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p080.4112.txt 80"
echo ""
echo "time used to run PTW-elev-0p080.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p081.4112.txt 81"
echo ""
echo "time used to run PTW-elev-0p081.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p082.4112.txt 82"
echo ""
echo "time used to run PTW-elev-0p082.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p083.4112.txt 83"
echo ""
echo "time used to run PTW-elev-0p083.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p084.4112.txt 84"
echo ""
echo "time used to run PTW-elev-0p084.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p085.4112.txt 85"
echo ""
echo "time used to run PTW-elev-0p085.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p086.4112.txt 86"
echo ""
echo "time used to run PTW-elev-0p086.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p087.4112.txt 87"
echo ""
echo "time used to run PTW-elev-0p087.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p088.4112.txt 88"
echo ""
echo "time used to run PTW-elev-0p088.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p089.4112.txt 89"
echo ""
echo "time used to run PTW-elev-0p089.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p090.4112.txt 90"
echo ""
echo "time used to run PTW-elev-0p090.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p091.4112.txt 91"
echo ""
echo "time used to run PTW-elev-0p091.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p092.4112.txt 92"
echo ""
echo "time used to run PTW-elev-0p092.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p093.4112.txt 93"
echo ""
echo "time used to run PTW-elev-0p093.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p094.4112.txt 94"
echo ""
echo "time used to run PTW-elev-0p094.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p095.4112.txt 95"
echo ""
echo "time used to run PTW-elev-0p095.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p096.4112.txt 96"
echo ""
echo "time used to run PTW-elev-0p096.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p097.4112.txt 97"
echo ""
echo "time used to run PTW-elev-0p097.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p098.4112.txt 98"
echo ""
echo "time used to run PTW-elev-0p098.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p099.4112.txt 99"
echo ""
echo "time used to run PTW-elev-0p099.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p100.4112.txt 100"
echo ""
echo "time used to run PTW-elev-0p100.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p101.4112.txt 101"
echo ""
echo "time used to run PTW-elev-0p101.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p102.4112.txt 102"
echo ""
echo "time used to run PTW-elev-0p102.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p103.4112.txt 103"
echo ""
echo "time used to run PTW-elev-0p103.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p104.4112.txt 104"
echo ""
echo "time used to run PTW-elev-0p104.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p105.4112.txt 105"
echo ""
echo "time used to run PTW-elev-0p105.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p106.4112.txt 106"
echo ""
echo "time used to run PTW-elev-0p106.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p107.4112.txt 107"
echo ""
echo "time used to run PTW-elev-0p107.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p108.4112.txt 108"
echo ""
echo "time used to run PTW-elev-0p108.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p109.4112.txt 109"
echo ""
echo "time used to run PTW-elev-0p109.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p110.4112.txt 110"
echo ""
echo "time used to run PTW-elev-0p110.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p111.4112.txt 111"
echo ""
echo "time used to run PTW-elev-0p111.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p112.4112.txt 112"
echo ""
echo "time used to run PTW-elev-0p112.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p113.4112.txt 113"
echo ""
echo "time used to run PTW-elev-0p113.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p114.4112.txt 114"
echo ""
echo "time used to run PTW-elev-0p114.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p115.4112.txt 115"
echo ""
echo "time used to run PTW-elev-0p115.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p116.4112.txt 116"
echo ""
echo "time used to run PTW-elev-0p116.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p117.4112.txt 117"
echo ""
echo "time used to run PTW-elev-0p117.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p118.4112.txt 118"
echo ""
echo "time used to run PTW-elev-0p118.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p119.4112.txt 119"
echo ""
echo "time used to run PTW-elev-0p119.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p120.4112.txt 120"
echo ""
echo "time used to run PTW-elev-0p120.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p121.4112.txt 121"
echo ""
echo "time used to run PTW-elev-0p121.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p122.4112.txt 122"
echo ""
echo "time used to run PTW-elev-0p122.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p123.4112.txt 123"
echo ""
echo "time used to run PTW-elev-0p123.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p124.4112.txt 124"
echo ""
echo "time used to run PTW-elev-0p124.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p125.4112.txt 125"
echo ""
echo "time used to run PTW-elev-0p125.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p126.4112.txt 126"
echo ""
echo "time used to run PTW-elev-0p126.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p127.4112.txt 127"
echo ""
echo "time used to run PTW-elev-0p127.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p128.4112.txt 128"
echo ""
echo "time used to run PTW-elev-0p128.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p129.4112.txt 129"
echo ""
echo "time used to run PTW-elev-0p129.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p130.4112.txt 130"
echo ""
echo "time used to run PTW-elev-0p130.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p131.4112.txt 131"
echo ""
echo "time used to run PTW-elev-0p131.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p132.4112.txt 132"
echo ""
echo "time used to run PTW-elev-0p132.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p133.4112.txt 133"
echo ""
echo "time used to run PTW-elev-0p133.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p134.4112.txt 134"
echo ""
echo "time used to run PTW-elev-0p134.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p135.4112.txt 135"
echo ""
echo "time used to run PTW-elev-0p135.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p136.4112.txt 136"
echo ""
echo "time used to run PTW-elev-0p136.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p137.4112.txt 137"
echo ""
echo "time used to run PTW-elev-0p137.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p138.4112.txt 138"
echo ""
echo "time used to run PTW-elev-0p138.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p139.4112.txt 139"
echo ""
echo "time used to run PTW-elev-0p139.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p140.4112.txt 140"
echo ""
echo "time used to run PTW-elev-0p140.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p141.4112.txt 141"
echo ""
echo "time used to run PTW-elev-0p141.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p142.4112.txt 142"
echo ""
echo "time used to run PTW-elev-0p142.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p143.4112.txt 143"
echo ""
echo "time used to run PTW-elev-0p143.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p144.4112.txt 144"
echo ""
echo "time used to run PTW-elev-0p144.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p145.4112.txt 145"
echo ""
echo "time used to run PTW-elev-0p145.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p146.4112.txt 146"
echo ""
echo "time used to run PTW-elev-0p146.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p147.4112.txt 147"
echo ""
echo "time used to run PTW-elev-0p147.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p148.4112.txt 148"
echo ""
echo "time used to run PTW-elev-0p148.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p149.4112.txt 149"
echo ""
echo "time used to run PTW-elev-0p149.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p150.4112.txt 150"
echo ""
echo "time used to run PTW-elev-0p150.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p151.4112.txt 151"
echo ""
echo "time used to run PTW-elev-0p151.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p152.4112.txt 152"
echo ""
echo "time used to run PTW-elev-0p152.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p153.4112.txt 153"
echo ""
echo "time used to run PTW-elev-0p153.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p154.4112.txt 154"
echo ""
echo "time used to run PTW-elev-0p154.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p155.4112.txt 155"
echo ""
echo "time used to run PTW-elev-0p155.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p156.4112.txt 156"
echo ""
echo "time used to run PTW-elev-0p156.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p157.4112.txt 157"
echo ""
echo "time used to run PTW-elev-0p157.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p158.4112.txt 158"
echo ""
echo "time used to run PTW-elev-0p158.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p159.4112.txt 159"
echo ""
echo "time used to run PTW-elev-0p159.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p160.4112.txt 160"
echo ""
echo "time used to run PTW-elev-0p160.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p161.4112.txt 161"
echo ""
echo "time used to run PTW-elev-0p161.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p162.4112.txt 162"
echo ""
echo "time used to run PTW-elev-0p162.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p163.4112.txt 163"
echo ""
echo "time used to run PTW-elev-0p163.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p164.4112.txt 164"
echo ""
echo "time used to run PTW-elev-0p164.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p165.4112.txt 165"
echo ""
echo "time used to run PTW-elev-0p165.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p166.4112.txt 166"
echo ""
echo "time used to run PTW-elev-0p166.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p167.4112.txt 167"
echo ""
echo "time used to run PTW-elev-0p167.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p168.4112.txt 168"
echo ""
echo "time used to run PTW-elev-0p168.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p169.4112.txt 169"
echo ""
echo "time used to run PTW-elev-0p169.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p170.4112.txt 170"
echo ""
echo "time used to run PTW-elev-0p170.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p171.4112.txt 171"
echo ""
echo "time used to run PTW-elev-0p171.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p172.4112.txt 172"
echo ""
echo "time used to run PTW-elev-0p172.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p173.4112.txt 173"
echo ""
echo "time used to run PTW-elev-0p173.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p174.4112.txt 174"
echo ""
echo "time used to run PTW-elev-0p174.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p175.4112.txt 175"
echo ""
echo "time used to run PTW-elev-0p175.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p176.4112.txt 176"
echo ""
echo "time used to run PTW-elev-0p176.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p177.4112.txt 177"
echo ""
echo "time used to run PTW-elev-0p177.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p178.4112.txt 178"
echo ""
echo "time used to run PTW-elev-0p178.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p179.4112.txt 179"
echo ""
echo "time used to run PTW-elev-0p179.4112.txt = $((SECONDS-ticks)) s"
echo ""

export ticks=${SECONDS}
new_step "./sweeper PTW-elev-0p180.4112.txt 180"
echo ""
echo "time used to run PTW-elev-0p180.4112.txt = $((SECONDS-ticks)) s"
echo ""

echo ""
echo "time used = ${SECONDS} s"
date

